/*
 * Copyright (c) Andreas Billmann <abi@geofroggerfx.de>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package de.geofroggerfx.ui.glyphs;

import de.jensd.fx.glyphs.GlyphIcons;

public enum ElusiveIcons implements GlyphIcons {

    ZOOM_OUT('\uE600'),
    ZOOM_IN('\uE601'),
    YOUTUBE('\uE602'),
    WRENCH_ALT('\uE603'),
    WRENCH('\uE604'),
    WORDPRESS('\uE605'),
    WHEELCHAIR('\uE606'),
    WEBSITE_ALT('\uE607'),
    WEBSITE('\uE608'),
    WARNING_SIGN('\uE609'),
    W3C('\uE60A'),
    VOLUME_UP('\uE60B'),
    VOLUME_OFF('\uE60C'),
    VOLUME_DOWN('\uE60D'),
    VKONTAKTE('\uE60E'),
    VIMEO('\uE60F'),
    VIEW_MODE('\uE610'),
    VIDEO_CHAT('\uE611'),
    VIDEO_ALT('\uE612'),
    VIDEO('\uE613'),
    VIADEO('\uE614'),
    USER('\uE615'),
    USD('\uE616'),
    UPLOAD('\uE617'),
    UNLOCK_ALT('\uE618'),
    UNLOCK('\uE619'),
    UNIVERSAL_ACCESS('\uE61A'),
    TWITTER('\uE61B'),
    TUMBLR('\uE61C'),
    TRASH_ALT('\uE61D'),
    TRASH('\uE61E'),
    TORSO('\uE61F'),
    TINT('\uE620'),
    TIME_ALT('\uE621'),
    TIME('\uE622'),
    THUMBS_UP('\uE623'),
    THUMBS_DOWN('\uE624'),
    TH_LIST('\uE625'),
    TH_LARGE('\uE626'),
    TH('\uE627'),
    TEXT_WIDTH('\uE628'),
    TEXT_HEIGHT('\uE629'),
    TASKS('\uE62A'),
    TAGS('\uE62B'),
    TAG('\uE62C'),
    STUMBLEUPON('\uE62D'),
    STOP_ALT('\uE62E'),
    STOP('\uE62F'),
    STEP_FORWARD('\uE630'),
    STEP_BACKWARD('\uE631'),
    STAR_EMPTY('\uE632'),
    STAR_ALT('\uE633'),
    STAR('\uE634'),
    STACKOVERFLOW('\uE635'),
    SPOTIFY('\uE636'),
    SPEAKER('\uE637'),
    SOUNDCLOUD('\uE638'),
    SMILEY_ALT('\uE639'),
    SMILEY('\uE63A'),
    SLIDESHARE('\uE63B'),
    SKYPE('\uE63C'),
    SIGNAL('\uE63D'),
    SHOPPING_CART_SIGN('\uE63E'),
    SHOPPING_CART('\uE63F'),
    SHARE_ALT('\uE640'),
    SHARE('\uE641'),
    SEARCH_ALT('\uE642'),
    SEARCH('\uE643'),
    SCREENSHOT('\uE644'),
    SCREEN_ALT('\uE645'),
    SCREEN('\uE646'),
    SCISSORS('\uE647'),
    RSS('\uE648'),
    ROAD('\uE649'),
    REVERSE_ALT('\uE64A'),
    RETWEET('\uE64B'),
    RETURN_KEY('\uE64C'),
    RESIZE_VERTICAL('\uE64D'),
    RESIZE_SMALL('\uE64E'),
    RESIZE_HORIZONTAL('\uE64F'),
    RESIZE_FULL('\uE650'),
    REPEAT_ALT('\uE651'),
    REPEAT('\uE652'),
    REMOVE_SIGN('\uE653'),
    REMOVE_CIRCLE('\uE654'),
    REMOVE('\uE655'),
    REFRESH('\uE656'),
    REDDIT('\uE657'),
    RECORD('\uE658'),
    RANDOM('\uE659'),
    QUOTES_ALT('\uE65A'),
    QUOTES('\uE65B'),
    QUESTION_SIGN('\uE65C'),
    QUESTION('\uE65D'),
    QRCODE('\uE65E'),
    PUZZLE('\uE65F'),
    PRINT('\uE660'),
    PODCAST('\uE661'),
    PLUS_SIGN('\uE662'),
    PLUS('\uE663'),
    PLAY_CIRCLE('\uE664'),
    PLAY_ALT('\uE665'),
    PLAY('\uE666'),
    PLANE('\uE667'),
    PINTEREST('\uE668'),
    PICTURE('\uE669'),
    PICASA('\uE66A'),
    PHOTO_ALT('\uE66B'),
    PHOTO('\uE66C'),
    PHONE_ALT('\uE66D'),
    PHONE('\uE66E'),
    PERSON('\uE66F'),
    PENCIL_ALT('\uE670'),
    PENCIL('\uE671'),
    PAUSE_ALT('\uE672'),
    PAUSE('\uE673'),
    PATH('\uE674'),
    PAPER_CLIP_ALT('\uE675'),
    PAPER_CLIP('\uE676'),
    OPENSOURCE('\uE677'),
    OK_SIGN('\uE678'),
    OK_CIRCLE('\uE679'),
    OK('\uE67A'),
    OFF('\uE67B'),
    NETWORK('\uE67C'),
    MYSPACE('\uE67D'),
    MUSIC('\uE67E'),
    MOVE('\uE67F'),
    MINUS_SIGN('\uE680'),
    MINUS('\uE681'),
    MIC_ALT('\uE682'),
    MIC('\uE683'),
    MAP_MARKER_ALT('\uE684'),
    MAP_MARKER('\uE685'),
    MALE('\uE686'),
    MAGNET('\uE687'),
    MAGIC('\uE688'),
    LOCK_ALT('\uE689'),
    LOCK('\uE68A'),
    LIVEJOURNAL('\uE68B'),
    LIST_ALT('\uE68C'),
    LIST('\uE68D'),
    LINKEDIN('\uE68E'),
    LINK('\uE68F'),
    LINES('\uE690'),
    LEAF('\uE691'),
    LASTFM('\uE692'),
    LAPTOP_ALT('\uE693'),
    LAPTOP('\uE694'),
    KEY('\uE695'),
    ITALIC('\uE696'),
    IPHONE_HOME('\uE697'),
    INSTAGRAM('\uE698'),
    INFO_SIGN('\uE699'),
    INDENT_RIGHT('\uE69A'),
    INDENT_LEFT('\uE69B'),
    INBOX_BOX('\uE69C'),
    INBOX_ALT('\uE69D'),
    INBOX('\uE69E'),
    IDEA_ALT('\uE69F'),
    IDEA('\uE6A0'),
    HOURGLASS('\uE6A1'),
    HOME_ALT('\uE6A2'),
    HOME('\uE6A3'),
    HEART_EMPTY('\uE6A4'),
    HEART_ALT('\uE6A5'),
    HEART('\uE6A6'),
    HEARING_IMPAIRED('\uE6A7'),
    HEADPHONES('\uE6A8'),
    HDD('\uE6A9'),
    HAND_UP('\uE6AA'),
    HAND_RIGHT('\uE6AB'),
    HAND_LEFT('\uE6AC'),
    HAND_DOWN('\uE6AD'),
    GUIDEDOG('\uE6AE'),
    GROUP_ALT('\uE6AF'),
    GROUP('\uE6B0'),
    GRAPH_ALT('\uE6B1'),
    GRAPH('\uE6B2'),
    GOOGLEPLUS('\uE6B3'),
    GLOBE_ALT('\uE6B4'),
    GLOBE('\uE6B5'),
    GLASSES('\uE6B6'),
    GLASS('\uE6B7'),
    GITHUB_TEXT('\uE6B8'),
    GITHUB('\uE6B9'),
    GIFT('\uE6BA'),
    GBP('\uE6BB'),
    FULLSCREEN('\uE6BC'),
    FRIENDFEED_RECT('\uE6BD'),
    FRIENDFEED('\uE6BE'),
    FOURSQUARE('\uE6BF'),
    FORWARD_ALT('\uE6C0'),
    FORWARD('\uE6C1'),
    FORK('\uE6C2'),
    FONTSIZE('\uE6C3'),
    FONT('\uE6C4'),
    FOLDER_SIGN('\uE6C5'),
    FOLDER_OPEN('\uE6C6'),
    FOLDER_CLOSE('\uE6C7'),
    FOLDER('\uE6C8'),
    FLICKR('\uE6C9'),
    FLAG_ALT('\uE6CA'),
    FLAG('\uE6CB'),
    FIRE('\uE6CC'),
    FILTER('\uE6CD'),
    FILM('\uE6CE'),
    FILE_NEW_ALT('\uE6CF'),
    FILE_NEW('\uE6D0'),
    FILE_EDIT_ALT('\uE6D1'),
    FILE_EDIT('\uE6D2'),
    FILE_ALT('\uE6D3'),
    FILE('\uE6D4'),
    FEMALE('\uE6D5'),
    FAST_FORWARD('\uE6D6'),
    FAST_BACKWARD('\uE6D7'),
    FACETIME_VIDEO('\uE6D8'),
    FACEBOOK('\uE6D9'),
    EYE_OPEN('\uE6DA'),
    EYE_CLOSE('\uE6DB'),
    EXCLAMATION_SIGN('\uE6DC'),
    EUR('\uE6DD'),
    ERROR_ALT('\uE6DE'),
    ERROR('\uE6DF'),
    ENVELOPE_ALT('\uE6E0'),
    ENVELOPE('\uE6E1'),
    EJECT('\uE6E2'),
    EDIT('\uE6E3'),
    DRIBBBLE('\uE6E4'),
    DOWNLOAD_ALT('\uE6E5'),
    DOWNLOAD('\uE6E6'),
    DIGG('\uE6E7'),
    DEVIANTART('\uE6E8'),
    DELICIOUS('\uE6E9'),
    DASHBOARD('\uE6EA'),
    CSS('\uE6EB'),
    CREDIT_CARD('\uE6EC'),
    COMPASS_ALT('\uE6ED'),
    COMPASS('\uE6EE'),
    COMMENT_ALT('\uE6EF'),
    COMMENT('\uE6F0'),
    COGS('\uE6F1'),
    COG_ALT('\uE6F2'),
    COG('\uE6F3'),
    CLOUD_ALT('\uE6F4'),
    CLOUD('\uE6F5'),
    CIRCLE_ARROW_UP('\uE6F6'),
    CIRCLE_ARROW_RIGHT('\uE6F7'),
    CIRCLE_ARROW_LEFT('\uE6F8'),
    CIRCLE_ARROW_DOWN('\uE6F9'),
    CHILD('\uE6FA'),
    CHEVRON_UP('\uE6FB'),
    CHEVRON_RIGHT('\uE6FC'),
    CHEVRON_LEFT('\uE6FD'),
    CHEVRON_DOWN('\uE6FE'),
    CHECK_EMPTY('\uE6FF'),
    CHECK('\uE700'),
    CERTIFICATE('\uE701'),
    CC('\uE702'),
    CARET_UP('\uE703'),
    CARET_RIGHT('\uE704'),
    CARET_LEFT('\uE705'),
    CARET_DOWN('\uE706'),
    CAR('\uE707'),
    CAMERA('\uE708'),
    CALENDAR_SIGN('\uE709'),
    CALENDAR('\uE70A'),
    BULLHORN('\uE70B'),
    BULB('\uE70C'),
    BRUSH('\uE70D'),
    BROOM('\uE70E'),
    BRIEFCASE('\uE70F'),
    BRAILLE('\uE710'),
    BOOKMARK_EMPTY('\uE711'),
    BOOKMARK('\uE712'),
    BOOK('\uE713'),
    BOLD('\uE714'),
    BLOGGER('\uE715'),
    BLIND('\uE716'),
    BELL('\uE717'),
    BEHANCE('\uE718'),
    BARCODE('\uE719'),
    BAN_CIRCLE('\uE71A'),
    BACKWARD('\uE71B'),
    ASL('\uE71C'),
    ARROW_UP('\uE71D'),
    ARROW_RIGHT('\uE71E'),
    ARROW_LEFT('\uE71F'),
    ARROW_DOWN('\uE720'),
    ALIGN_RIGHT('\uE721'),
    ALIGN_LEFT('\uE722'),
    ALIGN_JUSTIFY('\uE723'),
    ALIGN_CENTER('\uE724'),
    ADULT('\uE725'),
    ADJUST_ALT('\uE726'),
    ADJUST('\uE727'),
    ADDRESS_BOOK_ALT('\uE728'),
    ADDRESS_BOOK('\uE729'),
    ASTERISK('\uE72A');

    private final char character;

    private ElusiveIcons(char character) {
        this.character = character;
    }


    @Override
    public char getChar() {
        return character;
    }

    @Override
    public String unicodeToString() {
        return String.format("\\u%04x", (int) character);
    }

    @Override
    public String characterToString() {
        return Character.toString(character);
    }

    @Override
    public String getFontFamily() {
        return ElusiveIcon.FONT_FAMILY;
    }

}
